// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"log/slog"

	"server/internal/biz"
	"server/internal/conf"
	"server/internal/data"
	pkg "server/internal/pkg"
	"server/internal/server"
	"server/internal/service"

	"github.com/go-kratos/kratos/v3"
)

import (
	_ "go.uber.org/automaxprocs"
)

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confAi *conf.Ai, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	todoRepo := data.NewTodoRepo(dataData)
	todoUsecase := biz.NewTodoUsecase(todoRepo)
	todoService := service.NewTodoService(todoUsecase)
	kimiClient, err := pkg.NewKimiClient(confAi)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	kimiTranslator := pkg.NewKimiTranslator(kimiClient)
	translateUsecase := biz.NewTranslateUsecase(kimiTranslator)
	grammarUsecase := biz.NewGrammarUsecase(kimiClient)
	keepmarkService := service.NewKeepMarkService(translateUsecase, grammarUsecase)
	grpcServer := server.NewGRPCServer(confServer, todoService)
	httpServer := server.NewHTTPServer(confServer, todoService, keepmarkService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
